(define-module (mcp discovery)
  #:use-module (json)
  #:use-module (web response)
  #:export (discovery-handler))

(define (discovery-handler request)
  (let ((response-data
         `((name . "Guile ChangeFlow MCP Server")
           (version . "0.1.0")
           (protocol . "MCP/1.0")
           (capabilities . ((tools . #t)
                           (notifications . #f)))
           (tools . #(((name . "create_change_request")
                      (description . "Create a new change request in the Guile ChangeFlow system")
                      (inputSchema . ((type . "object")
                                     (properties . ((title . ((type . "string")
                                                              (description . "Title of the change request")))
                                                   (description . ((type . "string")
                                                                  (description . "Detailed description of the change")))))
                                     (required . #("title" "description")))))
                     ((name . "assess_risk")
                      (description . "Assess risk level for a change request")
                      (inputSchema . ((type . "object")
                                     (properties . ((changeId . ((type . "string")
                                                                 (description . "ID of the change request to assess")))))
                                     (required . #("changeId"))))))))))
    (values '((content-type . (application/json))
              (access-control-allow-origin . "*")
              (access-control-allow-methods . "GET, POST, OPTIONS")
              (access-control-allow-headers . "Content-Type"))
            (scm->json-string response-data))))