# Simplified Wrangler Configuration for Guile ChangeFlow
# Production-Ready Cloudflare Worker Deployment

name = "guile-changeflow-prod"
main = "worker.js"
compatibility_date = "2024-09-13"
compatibility_flags = ["nodejs_compat"]

# Production Environment
[env.production]
name = "guile-changeflow-prod"

# Staging Environment
[env.staging]
name = "guile-changeflow-staging"

# Development Environment
[env.development]
name = "guile-changeflow-dev"

# Global Variables
[vars]
WORKER_VERSION = "1.0.0"
MCP_PROTOCOL_VERSION = "2024-11-05"
ENVIRONMENT = "production"
LOG_LEVEL = "info"

# Production Variables
[env.production.vars]
ENVIRONMENT = "production"
CORS_ORIGINS = "*"
RATE_LIMIT_PER_MINUTE = "1000"

# Staging Variables
[env.staging.vars]
ENVIRONMENT = "staging"
CORS_ORIGINS = "*"
RATE_LIMIT_PER_MINUTE = "500"

# Development Variables
[env.development.vars]
ENVIRONMENT = "development"
CORS_ORIGINS = "*"
RATE_LIMIT_PER_MINUTE = "100"

# Build configuration
[build]
command = "echo 'No build step required for production worker'"

# Resource limits
[limits]
cpu_ms = 30000