name = "guile-changeflow-prod"
main = "worker.js"
compatibility_date = "2025-01-13"

# Account and deployment settings
account_id = "" # Will be filled in during deployment

# Custom domains (configured in Cloudflare dashboard)
# routes = []

# Environment variables (if needed)
# WARNING: These override Cloudflare dashboard values on deployment!
[vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
GITHUB_CLIENT_ID = "Ov23lir2JJgJffb51RPs"

# Workers Logs configuration
[observability]
enabled = true

# Sampling configuration for logs (needs to be enabled in dashboard)
# [[analytics_engine_datasets]]
# binding = "AE"

# KV storage for ITIL change requests
[[kv_namespaces]]
binding = "CHANGES_KV"
id = "changes-kv-namespace"
# Note: Will be created automatically during deployment

# For future Durable Objects
# [[durable_objects.bindings]]
# name = "CHANGE_STORAGE"
# class_name = "ChangeStorage"
# script_name = "worker"

# Staging settings (use with: wrangler deploy --env staging)
[env.staging]
name = "guile-changeflow-staging"
vars = { ENVIRONMENT = "staging", LOG_LEVEL = "info" }