name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
    paths:
      - 'mcp-server/**'
      - 'infra/cloudflare/**'
      - '.github/workflows/deploy-cloudflare.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Build Worker
      run: |
        echo "Building worker from source..."
        make build
        echo "✅ Worker built"

    - name: Create Version File
      run: |
        echo "Creating version file with commit SHA..."
        echo "${{ github.sha }}" > infra/cloudflare/.version
        echo "Deployed version: ${{ github.sha }}"

    - name: Deploy to Cloudflare Workers
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: |
        # Deploy to production on main branch pushes, staging for manual triggers without env specified
        if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
          ENVIRONMENT="production"
        else
          ENVIRONMENT="${{ github.event.inputs.environment || 'staging' }}"
        fi
        echo "Deploying ChangeFlow MCP to Cloudflare Workers ($ENVIRONMENT)..."
        cd infra/cloudflare

        if [ "$ENVIRONMENT" = "production" ]; then
          echo "Deploying to production..."
          wrangler deploy
        else
          echo "Deploying to staging..."
          wrangler deploy --env staging
        fi